## SVD
$$ Data_{m{\times}n} = U_{m{\times}m}{\Sigma}_{m{\times}n}V^T_{n{\times}n}$$

In [1]:
import numpy as np

In [2]:
U, sigma, VT = np.linalg.svd([[1, 1], [7, 7]])

In [4]:
U, U.shape

(array([[-0.14142136, -0.98994949],
        [-0.98994949,  0.14142136]]), (2, 2))

In [7]:
sigma, sigma.shape   #原本为对角矩阵，为了节省空间变成行向量

(array([1.00000000e+01, 2.82797782e-16]), (2,))

In [8]:
VT, VT.shape

(array([[-0.70710678, -0.70710678],
        [ 0.70710678, -0.70710678]]), (2, 2))

In [9]:
def get_data():
    return [
        [1,1,1,0,0],
        [2,2,2,0,0],
        [1,1,1,0,0],
        [5,5,5,0,0],
        [1,1,0,2,2],
        [0,0,0,3,3],
        [0,0,0,1,1],]

In [19]:
#获取数据并作SVD分解
data = get_data()
U, Sigma, VT = np.linalg.svd(data, full_matrices = True)
Sigma  #前三个奇异值要比后面两个大很多

array([9.72140007e+00, 5.29397912e+00, 6.84226362e-01, 4.11502614e-16,
       1.36030206e-16])

In [20]:
#构造对角矩阵
Sig3 = np.mat([[Sigma[0], 0, 0], [0,Sigma[1], 0], [0,0,Sigma[2]]])
Sig3

matrix([[9.72140007, 0.        , 0.        ],
        [0.        , 5.29397912, 0.        ],
        [0.        , 0.        , 0.68422636]])

In [16]:
#重构原始矩阵的近似矩阵
U[:,:3] * Sig3 * VT[:3,:], (U[:,:3] * Sig3 * VT[:3,:]).shape

matrix([[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          7.75989921e-16,  7.71587483e-16],
        [ 2.00000000e+00,  2.00000000e+00,  2.00000000e+00,
          3.00514919e-16,  2.77832253e-16],
        [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          2.18975112e-16,  2.07633779e-16],
        [ 5.00000000e+00,  5.00000000e+00,  5.00000000e+00,
          3.00675663e-17, -1.28697294e-17],
        [ 1.00000000e+00,  1.00000000e+00, -5.48397422e-16,
          2.00000000e+00,  2.00000000e+00],
        [ 3.21319929e-16,  4.43562065e-16, -3.48967188e-16,
          3.00000000e+00,  3.00000000e+00],
        [ 9.71445147e-17,  1.45716772e-16, -1.52655666e-16,
          1.00000000e+00,  1.00000000e+00]])